### ISSUE TITLE
Compatibility with .NET 5

### ISSUE THREAD

**Issue by amazingalek** [kevinjpetersen/BlazorQuery#4]
Thanks for this awesome project. Unfortunately it's not compatible with .NET 5 Blazor projects.

My forked version of BlazorQuery is migrated to .NET 5, using [this migration guide](https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50): https://github.com/Abel-Solutions/BlazorQuery

I made a PR: #5

**Comment by kevinjpetersen** [comment]
Hello @amazingalek 

Thank you so much for using BlazorQuery, and I really appreciate your PR, which I also just now approved and merged!

I wish I had more time to work on BlazorQuery as I myself really like it too, but unfortunately I have alot of IRL work I'm currently doing.. :(

Thanks again!

**Comment by amazingalek** [comment]
Thanks, happy to help! I'll let you know if I add any new features to BlazorQuery! :)

**Comment by amazingalek** [comment]
@kevinjpetersen wanna update the NuGet package? :)

**Comment by kevinjpetersen** [comment]
@amazingalek I have now updated the NuGet with version 0.0.3. It might take an hour or so before it shows up in the NuGet Manager in Visual Studio, but it should be available here already: https://www.nuget.org/packages/BlazorQuery/

**Comment by amazingalek** [comment]
Awesome, thanks!
